# TP n°4 : Listes



___________________________________________________________________________
## Liste : premier et dernier



On se donne une liste d'entiers `L`. Afficher sur une même ligne et séparés par une espace le premier élément de la liste et le dernier élément de la liste. Par exemple,


- si `L = [31, 12, 81, 9, 65]` alors l'affichage est : `31 65`

- si `L = [42]` alors l'affichage est : `42 42`



In [12]:
L = [31, 12, 81, 9, 65]
print(L[0], L[-1])

L = [42]
print(L[0], L[-1])

31 65
42 42


___________________________________________________________________________
## Liste : $k$-ème élément



On se donne une liste d'entiers `L`. On suppose que la liste `L` contient au moins deux éléments. On donne un entier $k\geq 1$. Afficher le $k$-ème élément de la liste si cet élément existe sinon, on affiche le message *rang invalide*.

Exemples d'exécution :


- `L = [31, 12, 81, 9, 65]`, `k = 3` -> `81`

- `L = [31, 12, 81, 9, 65]`, `k = 42` -> `rang invalide`



In [13]:
L = [31, 12, 81, 9, 65]
for _ in range(2):
    k = int(input())
    if k > len(L): print("rang invalide")
    else: print(L[k - 1])

3
81
42
rang invalide


___________________________________________________________________________
## Liste de trois éléments



On donne un entier $x$ et on compte de 10 en 10 trois fois à partir de x. Construire la liste $L$ qui contient les trois nombres obtenus. Par exemple, si x=42, la liste est formée des trois entiers 42, 52 et 62.



In [14]:
x = int(input())
L = [x + a for a in range(0, 30, 10)]
print(L)

42
[42, 52, 62]


___________________________________________________________________________
## Changer certains éléments d'une liste



On donne une liste `L` d'entiers ayant au moins 3 valeurs. Modifier cette liste pour que les éléments $x$ de la liste qui sont


- en première position

- en deuxième position

- en dernière position

soient remplacés par $10x$. Par exemple, si `L = [31, 12, 81, 9, 65] ` alors, après modification, on aura `L = [310, 120, 81, 9, 650]`.



In [15]:
L = [31, 12, 81, 9, 65]
L[0] *= 10
L[1] *= 10
L[-1] *= 10
print(L)

[310, 120, 81, 9, 650]


___________________________________________________________________________
## Test de présence



On donne


- une liste d'entiers `L`

- un entier `x`

On rappelle que `x in L` est un booléen qui teste la présence de `x` dans la liste `L`.

Construire un booléen `ok` qui vaut `True` si l'un des trois entiers `x`, `x - 1` et `x + 1` est dans la liste et `False` sinon. Exemple avec `x = 42` :


- si `L =[31, 12, 42, 9, 65]` alors `ok = True`

- si `L =[31, 12, 81, 43]` alors `ok = True`

- si `L =[41]` alors `ok = True`

- si `L =[31, 12, 81, 9, 65]` alors `ok = False`



In [18]:
x = int(input())

L = [31, 12, 42, 9, 65]
ok = x - 1 in L or x in L or x + 1 in L
print(ok)

L = [31, 12, 81, 43]
ok = x - 1 in L or x in L or x + 1 in L
print(ok)

L = [41]
ok = x - 1 in L or x in L or x + 1 in L
print(ok)

L = [31, 12, 81, 9, 65]
ok = x - 1 in L or x in L or x + 1 in L
print(ok)

42
True
True
True
False


___________________________________________________________________________
## Liste des solutions de l'équation du second degré



Soit l'équation du second degré $ax^2+bx+c=0$. On supposera que $a,b,c$ sont des entiers, que $a$ est non nul et que l'inconnue $x$ est un nombre réel.

On rappelle le code Python de la résolution  d'une équation du second degré :



In [ ]:
a = 2
b = -3
c = 1
delta = b*b -4*a*c
if delta >0:
    print("2 solutions distinctes :")
    print("x1 =", (-b - delta**0.5)/(2.*a))
    print("x2 =", (-b + delta**0.5)/(2.*a))
else:
    if delta == 0:
        print("une seule solution")
        print("x =", (-b)/(2.*a))
    else:
        print("Aucune solution")


Adapter le code précédent pour construire la liste S contenant toutes les solutions de l'équation. Par exemple,


- si a = 2, b=-3 et c = 1 alors   `S = [1, 0.5]`

- si a = 4, b=4 et c = 1 alors   `S = [-0.5]`

- si a = 4, b=4 et c = 4 alors   `S` est la liste vide



In [22]:
for _ in range(3):
    a = int(input())
    b = int(input())
    c = int(input())
    delta = b*b -4*a*c
    if delta >0:
        print("2 solutions distinctes :")
        S = [(-b - delta**0.5)/(2.*a), (-b + delta**0.5)/(2.*a)]
    elif delta == 0:
        print("une seule solution")
        S = [(-b)/(2.*a)]
    else:
        print("Aucune solution")
        S = []
    if S != []: print(S)
    print()

2
-3
1
2 solutions distinctes :
[0.5, 1.0]

4
4
1
une seule solution
[-0.5]

4
4
4
Aucune solution



___________________________________________________________________________
## Tester les mois de 31 jours avec une liste



Construire une liste littérale `jours` telle que pour chaque numéro `i` entre 1 et 12 d'un mois d'une année non bissextile, `jours[i]` désigne le nombre de jours du mois de numéro `i`. Par exemple, `jours[10] = 31`.

En déduire une variable booléenne `mois31` qui, étant donné un numéro de mois `i`, vaut `True` si le mois de numéro `i` possède 31 jours et `False` sinon.



In [24]:
i = int(input())
jours = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
mois31 = jours[i + 1]
print(mois31)

10
31


___________________________________________________________________________
## Somme des multiples de 10



On donne une liste `L` d'entiers. Calculer la somme `s` des éléments de `L` qui sont des multiples de 10. Par exemple, si `L = [310, 12, 8100, 90, 31]` alors `s = 8500`.



In [28]:
L = [310, 12, 8100, 90, 31]
s = sum([ent for ent in L if ent % 10 == 0])
print(s)

8500


___________________________________________________________________________
## Somme suivant les indices impairs



On donne une liste `L` d'entiers. Calculer la somme `s` des éléments de `L` dont l'indice est impair. Par exemple, si `L = [31, 12, 81, 9, 31]` alors `s = 21`.



In [30]:
L = [31, 12, 81, 9, 31]
s = sum([L[rang] for rang in range(len(L)) if rang % 2 == 1])
print(s)

21


___________________________________________________________________________
## Modifier une liste en multipliant par 10



On donne une liste d'entiers. Modifier cette liste pour que chaque élément $x$ de la liste soit remplacé par $10x$. Par exemple, si `L = [31, 12, 81, 9, 65] ` alors, après modification, on aura `L = [310, 120, 810, 90, 650]`.



In [31]:
L = [31, 12, 81, 9, 65]
L = [10*x for x in L]
print(L)

[310, 120, 810, 90, 650]


___________________________________________________________________________
## Calcul du minimum



On donne une liste L d'entiers. Calculer le plus petit élément `mini` de la liste. Par exemple, si `L = [31, 9, 81, 9, 31]` alors `mini = 9`.



In [32]:
L = [31, 9, 81, 9, 31]
mini = L[0]
for x in L:
    if x < mini: mini = x
print(mini)

# Peut aussi s'écrire 'print(min(L))'

9


___________________________________________________________________________
## Indice du minimum



On donne une liste d'entiers. Déterminer un indice `i_mini` correspondant au plus petit élément `mini` de la liste. Par exemple


- si `L = [31, 12, 81, 9, 31]` alors `mini = 9` et `i_mini = 3`

- si `L = [31, 9, 81, 9, 31]` alors `mini = 9` et `i_mini = 1` (ou encore `i_mini = 3`)



In [36]:
L = [31, 12, 81, 9, 31]
mini = L[0]
for rang in range(len(L)):
    x = L[rang]
    if x < mini: mini, i_mini = x, rang
print(i_mini)

L = [31, 9, 81, 9, 31]
mini = L[0]
for rang in range(len(L)):
    x = L[rang]
    if x < mini: mini, i_mini = x, rang
print(i_mini)

# Peut aussi s'écrire 'print(L.index(min(L)))'

3
1


___________________________________________________________________________
## Minimum des entiers d'indices pairs



On donne une liste `L` d'entiers. Calcul `mini_pairs` le plus petit des éléments d'indices pairs de la liste. Par exemple, si `L = [81, 32, 12, 9, 10, 65, 46]` alors `mini_pairs = 10`.



In [38]:
L = [81, 32, 12, 9, 10, 65, 46]
mini_pairs = L[0]
for rang in range(len(L)):
    x = L[rang]
    if x < mini_pairs and rang % 2 == 0: mini_pairs = x
print(mini_pairs)

10


___________________________________________________________________________
## Valeurs paires d'une liste



Soit une liste `L` d'entiers. Séparer cette liste en deux listes :


- la liste `P` des entiers pairs de `L`

- la liste `I` des entiers impairs de `L`

Par exemple, si `L = [31, 12, 9, 65, 81, 42]` alors `P = [12, 42]` et `I = [31, 9, 65, 81]`



In [41]:
L = [31, 12, 9, 65, 81, 42]
def lEnt(L, reste):
    return [ent for ent in L if ent % 2 == reste]
P, I = lEnt(L, 0), lEnt(L, 1)
print(P, I, sep = "\n")

[12, 42]
[31, 9, 65, 81]


___________________________________________________________________________
## Indices pairs



Soit une liste `L`. Séparer cette liste en deux listes :


- la liste `IP` des éléments de `L` d'indices pairs

- la liste `II` des éléments de `L` d'indices impairs

Par exemple, si `L = [31, 12, 9, 65, 81, 42]` alors `IP = [31, 9, 81]` et `II = [12, 65, 42]`.



In [42]:
L = [31, 12, 9, 65, 81, 42]
def lEnt(L, reste):
    return [L[rang] for rang in range(reste, len(L), 2)]
IP, II = lEnt(L, 0), lEnt(L, 1)
print(IP, II, sep = "\n")

[31, 9, 81]
[12, 65, 42]


___________________________________________________________________________
## Echanger deux variables



Étant donné deux variables $x$ et $y$, on veut permuter leurs valeurs. Par exemple si au départ $x=81$ et $y=31$ alors, après échange, on doit avoir: $x=31$ et $y=81$. On pourra compléter le code ci-dessous :



In [45]:
x=81
y=31
print(x,y)

# Votre code ICI

print(x,y)

81 31
31 81


Bien sûr votre code doit fonctionner correctement si on donne d'autres valeurs à `x` et `y` aux lignes 1 et 2.

On fera comme lorsqu'on veut échanger deux étiquettes A et B placées sur des objets : on utilise une étiquette de nommage temporaire.



In [46]:
x, y = 81, 31
print(x, y)

y, x = [x, y]

print(x, y)

81 31
31 81


___________________________________________________________________________
## Echanger les extrémités d'une liste



*Cette question nécessite d'adapter aux éléments d'une liste le code d'échange des valeurs de deux variables.*

Soit une liste `L`. Modifier `L` pour que son premier élément et son dernier élément soient échangés. Par exemple, si `L = [31, 12, 9, 65, 81]` alors après échange, on aura  `L = [81, 12, 9, 65, 31]`.



In [47]:
L = [31, 12, 9, 65, 81]
L[0], L[-1] = L[-1], L[0]
print(L)

[81, 12, 9, 65, 31]


___________________________________________________________________________
## Echanger côte à côte



Soit une liste `L`. Modifier `L` pour que


- le 1er élément et le 2ème élément soient échangés de position

- le 3ème élément et le 4ème élément soient échangés de position

- ...

- et ainsi de suite jusqu'à ce que plus aucun échange ne soit possible.

Par exemple,


- si `L = [31, 12, 9, 65, 81, 42]` alors, après échanges, `L = [12, 31, 65, 9,42, 81]`

- si `L = [31, 12, 9, 65, 81]` alors, après échanges, `L = [12, 31, 65, 9, 81]`

- si `L = [31]` alors, après échange, `L = [31]`



In [50]:
def echange(L):
    for rang in range(0, len(L) - 1, 2):
        L[rang], L[rang + 1] = L[rang + 1], L[rang]
    return L
print(echange([31, 12, 9, 65, 81, 42]), echange([31, 12, 9, 65, 81]), echange([31]), sep = "\n")

[12, 31, 65, 9, 42, 81]
[12, 31, 65, 9, 81]
[31]


___________________________________________________________________________
## Inverser une liste



Soit une liste `L`. Modifier `L` pour que


- le 1er élément et le dernier élément soient échangés de position

- le 2ème élément et l'avant-dernier élément soient échangés de position

- ...

- et ainsi de suite jusqu'à ce que tous les échanges possibles soient effectués.

Par exemple,


- si `L = [31, 12, 9, 65]` alors, après échanges, `L = [65, 9, 12, 31]`

- si `L = [31, 12, 81, 9, 65]` alors, après échanges, `L = [65, 9, 81, 12, 31]`

- si `L = [31]` alors, après échange, `L = [31]`



In [57]:
def inverse(L):
    for rang in range(len(L)//2):
        L[rang], L[-rang - 1] = L[-rang - 1], L[rang]
    return L
print(inverse([31, 12, 9, 65]), inverse([31, 12, 81, 9, 65]), inverse([31]), sep = "\n")

# Peut aussi s'écrire 'L.reverse()'
                    # 'print(L)'

[65, 9, 12, 31]
[65, 9, 81, 12, 31]
[31]


___________________________________________________________________________
## Décompte pair/impair



On donne une liste `L` d'entiers et on demande de calculer


- le nombre  `n_pair` d'indices `i` tel que l'élément `L[i]` est pair

- le nombre  `n_impair` d'indices `i` tel que l'élément `L[i]` est impair

Par exemple, si `L = [31, 12, 9, 65, 81, 42]` alors `n_pair = 2` et `n_impair = 4`.



In [60]:
L = [31, 12, 9, 65, 81, 42]
n_pair, n_impair = 0, 0
for x in L:
    if x % 2 == 0: n_pair += 1
    else: n_impair += 1
print(n_pair, n_impair, sep = "\n")

2
4


___________________________________________________________________________
## Minimum présent une seule fois



On donne une liste `L` d'entiers. Soit `mini` le plus petit élément de la liste. Construire une variable `miniUnique` qui vaut `True` ou `False` selon que `mini` apparaît une seule fois dans la liste ou au contraire, plusieurs fois. Par exemple


- si `L = [31, 12, 81, 9, 31]` alors `mini = 9` et  `miniUnique=True` ;

- si `L = [31, 9, 81, 9, 31]` alors `mini = 9` et `miniUnique=False`.



In [59]:
def test(L):
    return L.count(min(L)) == 1
print(test([31, 12, 81, 9, 31]), test([31, 9, 81, 9, 31]), sep = "\n")

True
False
